name: CodeQuality

on:
  push:
    branch: 
      - main

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      - name: Cache npm dependecies 
        uses: actions/cache@v2
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install ci
        run: |
          npm ci 
      
      - name: Calc coverage
        run : |
          npm run test